[workspace]
resolver = "2"
members = [
  "crates/core",
  "crates/plato",
  "crates/importer",
  "crates/fetcher",
  "crates/emulator",
]

[profile.release-minsized]
inherits = "release"
panic = "abort"
codegen-units = 1
opt-level = "z"
lto = true
strip = true
