selected-library = 0
keyboard-layout = "English"
frontlight = true
wifi = false
inverted = false
sleep-cover = true
auto-share = false
button-scheme = "natural"
auto-suspend = 30.0
auto-power-off = 3.0
time-format = "%H:%M"
date-format = "%A, %B %-d, %Y"
external-urls-queue = "bin/article_fetcher/urls.txt"

[[libraries]]
name = "On Board"
path = "/mnt/onboard"
mode = "database"
sort-method = "opened"
first-column = "title-and-author"
second-column = "progress"
thumbnail-previews = true

[[libraries.hooks]]
path = "Articles"
program = "bin/article_fetcher/article_fetcher"
sort-method = "added"
first-column = "title-and-author"
second-column = "progress"

[[libraries]]
name = "Removable"
path = "/mnt/sd"
mode = "database"
sort-method = "opened"
first-column = "title-and-author"
second-column = "progress"
thumbnail-previews = true

[[libraries]]
name = "Dropbox"
path = "/mnt/onboard/.kobo/dropbox"
mode = "database"
sort-method = "opened"
first-column = "title-and-author"
second-column = "progress"
thumbnail-previews = true

[[libraries]]
name = "KePub"
path = "/mnt/onboard/.kobo/kepub"
mode = "database"
sort-method = "opened"
first-column = "title-and-author"
second-column = "progress"
thumbnail-previews = true

[intermissions]
suspend = "logo:"
power-off = "logo:"
share = "logo:"

[home]
address-bar = false
navigation-bar = true
max-levels = 3
max-trash-size = 33554432

[reader]
finished = "close"
south-east-corner = "go-to-page"
bottom-right-gesture = "toggle-dithered"
south-strip = "toggle-bars"
west-strip = "previous-page"
east-strip = "next-page"
strip-width = 0.6000000238418579
corner-width = 0.4000000059604645
font-path = "/mnt/onboard/fonts"
font-family = "Libertinus Serif"
font-size = 11.0
min-font-size = 5.5
max-font-size = 16.5
text-align = "left"
margin-width = 8
min-margin-width = 0
max-margin-width = 10
line-height = 1.2000000476837158
continuous-fit-to-width = true
ignore-document-css = false
dithered-kinds = ["jpeg", "jpg", "png", "cbz"]

[reader.paragraph-breaker]
hyphen-penalty = 50
stretch-tolerance = 1.2599999904632568

[reader.refresh-rate]
regular = 8
inverted = 2

[import]
unshare-trigger = true
startup-trigger = true
sync-metadata = true
metadata-kinds = ["djvu", "epub", "pdf"]
allowed-kinds = ["txt", "oxps", "xps", "mobi", "djvu", "cbz", "pdf", "epub", "fb2"]

[dictionary]
margin-width = 4
font-size = 11.0

[sketch]
save-path = "Sketches"
notify-success = true

[sketch.pen]
size = 2
color = 0
dynamic = true
amplitude = 4.0
min-speed = 0.0
max-speed = 1670.0

[calculator]
font-size = 8.0
margin-width = 2
history-size = 4096

[battery]
warn = 10.0
power-off = 3.0

[frontlight-levels]
intensity = 0.0
warmth = 0.0

[ao3]
remember-me = false
remember-username = false
username = "testUser"
password = "superFakePass123"
faves = [["fake fave search", "https://fakeo3.org/tags/super-fake"]]
work-display = "Short"
screenshot-button = false
